import Link from "next/link";
import { HelpLink } from "@/components/help/HelpLink";
import { redirect } from "next/navigation";
import { NotPermitted } from "@/components/NotPermitted";
import { can } from "@/lib/rbac";
import { getActiveSession, visibleEntityIds } from "@/lib/session";
import { DATASET_LABEL, type Dataset } from "@/services/exports";

const BLURB: Record<Dataset, string> = {
  risks: "Every risk with its inherent and residual rating, mitigations, and the acceptance in force.",
  assessments: "Every assessment with its type, status, score and dates.",
  "ai-register": "Every AI system, its stage and owner, and what is outstanding against it.",
  ropa: "Every processing activity in Article 30 order, with the gaps in each record named so you can see what an inspection would find.",
  "third-parties": "Every processor with the agreement in force, its expiry, and what is missing against Article 28.",
  breaches: "Every breach with both statutory decisions and the reasoning for each, including the ones judged not notifiable.",
  trends: "Twelve months of posture: risks raised and closed, assessments decided, how long decisions took.",
  countries: "Adequacy and transfer risk per destination, with when each was last checked.",
  audit: "The complete record of who did what, with the hash chain, so a recipient can verify it themselves.",
};

export default async function ExportsPage() {
  const active = await getActiveSession();
  if (!active) redirect("/sign-in");

  if (!can(active.membership.grants, "record.read")) {
    return (
      <NotPermitted
        what="Exports"
        organisationName={active.membership.organisationName}
      />
    );
  }

  const mayExportAudit = can(active.membership.grants, "audit.export");
  // A complete chain is what makes an audit export verifiable, and an
  // entity-scoped viewer cannot have one.
  const wholeChain = visibleEntityIds(active, "audit.export") === null;

  return (
    <main className="mx-auto max-w-3xl space-y-8 px-6 py-12">
      <header className="space-y-2 border-b border-line pb-6">
        <Link href="/app" className="text-xs text-ink-soft hover:text-brand">
          ← {active.membership.organisationName}
        </Link>
        <h1 className="text-2xl font-semibold tracking-tight">Exports</h1>
        <p className="max-w-prose text-sm text-ink-soft">
          Spreadsheets, for when somebody asks you for one. Each covers what you
          can see, and each is recorded in the audit log — including this page.
        </p>
      </header>

      <HelpLink topic="exports" />

      <ul className="divide-y divide-line overflow-hidden rounded border border-line bg-surface">
        {(Object.keys(DATASET_LABEL) as Dataset[])
          .filter((d) => d !== "audit" || mayExportAudit)
          .map((d) => (
            <li key={d} className="flex flex-wrap items-center justify-between gap-3 px-4 py-3.5">
              <div className="min-w-0">
                <p className="font-medium">{DATASET_LABEL[d]}</p>
                <p className="text-xs text-ink-soft">{BLURB[d]}</p>
                {d === "audit" && !wholeChain ? (
                  <p className="mt-1 text-xs text-amber-900">
                    Yours will be an extract limited to your entities. The hash
                    chain cannot be verified from a partial export, and the file
                    says so.
                  </p>
                ) : null}
              </div>
              <a
                href={`/api/export/${d}`}
                className="shrink-0 rounded border border-line bg-surface px-3 py-1.5 text-sm hover:border-brand focus-visible:outline-2 focus-visible:outline-brand"
              >
                Download CSV
              </a>
            </li>
          ))}
      </ul>

      <section className="space-y-2">
        <h2 className="text-sm font-semibold uppercase tracking-wider text-ink-soft">
          Documents
        </h2>
        <p className="max-w-prose text-sm text-ink-soft">
          These are data, not documents. A rendered DPIA or a formatted board
          report is generated by the Waivern Compliance Portal from the facts
          this platform publishes — building a second document generator here
          would duplicate it, and the two would eventually disagree.
        </p>
      </section>
    </main>
  );
}
